# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

- powershell: |
   (Get-Item "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe").VersionInfo 
  displayName: 'We want to know the Chrome version installed on this darned machine'

- pwsh: |
    chromeDriver -v
  displayName: Echo Chrome WebDriver version
