# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

- powershell: |
   $ver = ((Get-Item "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe").VersionInfo).ProductVersion
   echo "##vso[task.setvariable variable=ChromeVersion;isOutput=true]$ver"
  name: GetChromeVersion
  displayName: 'We want to know the Chrome version installed on this darned machine'

- script: webdrivermanager chrome:$(GetChromeVersion.ChromeVersion) --linkpath AUTO
  displayName: 'Manage Chrome webdriver version'
